### ISSUE TITLE
Implement "heartbeat" - a scheduler that executes a group of health checks

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-metrics#19]
Implement app "heartbeat" - a configurable scheduler that periodically executes a group of health checks, sending results to registered listeners. Configuration may look like this, with all config nodes having default values:

```yaml
heartbeat:
  initialDelayMs: 1000
  fixedDelayMs: 5000
  threadPoolSize: 3
  healthCheckTimeoutMs: 2000
  healthChecks: # default - all; TODO: support regexp to match multiple healthchecks
     - "jdbc.datasource.myapp" 
     - "myappcheck"
```
Starting the heartbeat is outside the scope of this task. There will be a separate task for that once we finish the core [API](https://github.com/bootique/bootique/pull/192) for running multiple commands at once.
