### ISSUE TITLE
Heartbeat to support skipping individual health checks

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-metrics#40]
Currently heartbeat has a single execution schedule (`heartbeat.fixedDelay`) for the entire collection of health checks. Sometimes it is needed to customize the delay per health check. E.g. some external systems would limit incoming requests. So let's allow `fixedDelay` to be applied at the health check level in addition to the global heartbeat level. 

While we are at it, we can apply a few other parameters at two levels as well: `initialDelay`, `healthCheckTimeout`.

(Note a recent key renaming per #41)

**Comment by andrus** [comment]
Unfortunately implementing individual heartbeat delays per health check is not as simple. It will require individual schedulers, and will not allow for aggregated reporting. I suppose we can cheat a bit and keep every check on the same scheduler, but allow some checks to skip "heartbeats", allowing to slow them down. E.g.:

```yaml
heartbeat:
   healthChecks:
      - check1
      - check2
         skipHeartbeats: 2 # run every 3rd heartbeat
```
